name: KingPlugin
version: 1.0
main: com.rafalohaki.kingplugin.KingPlugin
api-version: 1.19
author: rafalohaki
description: A plugin that allows players to become the king of the server.
commands:
  king:
    description: Crown a player as the king.
    usage: /king <player>
